### ISSUE TITLE
spelling "tunning"

### ISSUE THREAD

**Issue by dansteingart** [rohbotics/pifi#18]
PiFi is great. Thank you. Was exactly what I wanted and a super way to learn `mpd` to boot.

![image](https://user-images.githubusercontent.com/152047/72683839-34539b80-3aa9-11ea-9f0a-ba9585e93f9a.png)

Small spelling error in interface. `TUNNING` should be `TUNING`

**Comment by rohbotics** [comment]
Hi @dansteingart I think you have the wrong pifi :) This one is a wifi management system.

**Comment by dansteingart** [comment]
whoops sorry!
